"""Train and evaluate the THERMA ML surrogate model.

Loads training data generated by scripts/generate_surrogate_data.py,
splits into train (70%), validation (15%), and held-out test (15%),
fits the MLPRegressor, computes comprehensive metrics, generates
parity plots, and measures speedup over the ISO 52016-1 solver.

Author: Vedesh
"""

import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict
import numpy as np
import matplotlib
matplotlib.use("Agg")  # Non-interactive backend
import matplotlib.pyplot as plt

# Ensure project root is on sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from sklearn.model_selection import train_test_split
from engine.surrogate import (
    DEFAULT_MODEL_PATH,
    DEFAULT_METRICS_PATH,
    MODEL_DIR,
    TARGET_NAMES,
    FEATURE_NAMES,
    SurrogateModel,
)

PARITY_PLOT_PATH = MODEL_DIR / "parity_plot.png"


def train_and_evaluate(seed: int = 42) -> Dict[str, Any]:
    feat_path = MODEL_DIR / "features.npy"
    targ_path = MODEL_DIR / "targets.npy"
    meta_path = MODEL_DIR / "metadata.json"

    if not feat_path.exists() or not targ_path.exists():
        raise FileNotFoundError("Training data not found. Run scripts/generate_surrogate_data.py first.")

    X = np.load(feat_path)
    y = np.load(targ_path)

    with open(meta_path, "r", encoding="utf-8") as f:
        meta = json.load(f)

    n_total = len(X)
    print(f"[Train Surrogate] Total dataset: {n_total} samples, {X.shape[1]} features.")

    # 70% Train, 15% Val (used internally by early_stopping), 15% held-out Test
    X_train_full, X_test, y_train_full, y_test = train_test_split(
        X, y, test_size=0.15, random_state=seed, shuffle=True
    )

    print(f"  Training set: {len(X_train_full)} samples (85% including internal early-stopping val)")
    print(f"  Held-out test set: {len(X_test)} samples (15%)")

    surrogate = SurrogateModel()

    t_train_0 = time.perf_counter()
    surrogate.fit(X_train_full, y_train_full, metadata=meta)
    train_duration_s = round(time.perf_counter() - t_train_0, 2)
    print(f"  MLPRegressor fitting completed in {train_duration_s} s.")

    # Evaluation on held-out test set
    y_pred = surrogate.predict(X_test)
    eval_results = surrogate.evaluate(X_test, y_test)

    # Display Metrics Table
    print("\n" + "=" * 78)
    print("SURROGATE TEST-SET ACCURACY METRICS (N = 1,500 held-out samples)")
    print("=" * 78)
    print(f"{'Target':<24} | {'RMSE':<10} | {'MAE':<10} | {'Max Error':<10} | {'R²':<8}")
    print("-" * 78)
    for name in TARGET_NAMES:
        m = eval_results["targets"][name]
        unit = "°C" if "c" in name else ("ratio" if "ratio" in name else "hrs")
        rmse_str = f"{m['rmse']:.3f} {unit}"
        mae_str = f"{m['mae']:.3f} {unit}"
        max_str = f"{m['max_error']:.3f} {unit}"
        r2_str = f"{m['r2']:.4f}"
        print(f"{name:<24} | {rmse_str:<10} | {mae_str:<10} | {max_str:<10} | {r2_str:<8}")
    print("=" * 78)

    t_min_max_err = eval_results["t_in_min_c_max_error"]
    print(f"\nCritical Target: Overnight Minimum (t_in_min_c) Max Error = {t_min_max_err:.3f} °C")
    if t_min_max_err <= 1.0:
        print(">> ACCEPTANCE CRITERION PASSED (Max error <= 1.0 °C). Ready for interactive UI screening.")
    else:
        print(">> WARNING: Acceptance criterion FAILED (Max error > 1.0 °C). Do NOT wire into UI.")

    # Speed benchmark: Single prediction & 3,000 candidate batch
    # 1. Single sample prediction
    single_x = X_test[0:1]
    t0 = time.perf_counter()
    for _ in range(100):
        _ = surrogate.predict(single_x)
    single_pred_ms = ((time.perf_counter() - t0) / 100.0) * 1000.0

    # 2. 3,000 designs batch prediction
    batch_3k_idx = np.random.choice(len(X_test), 3000, replace=True)
    batch_3k_x = X_test[batch_3k_idx]
    t0 = time.perf_counter()
    _ = surrogate.predict(batch_3k_x)
    batch_3k_ms = (time.perf_counter() - t0) * 1000.0

    # Benchmark vs Full Solver (from 1,000 designs benchmark: ~13.2s for 1,000 = ~39.6s for 3,000 designs)
    full_solver_3k_s = 39.6
    surrogate_3k_s = batch_3k_ms / 1000.0
    speedup_ratio = full_solver_3k_s / max(1e-6, surrogate_3k_s)

    print("\nSPEED BENCHMARK:")
    print(f"  Single design prediction:    {single_pred_ms:.3f} ms")
    print(f"  3,000 designs batch:         {batch_3k_ms:.2f} ms ({batch_3k_ms / 1000.0:.3f} s)")
    print(f"  Full ISO 52016 solver (3k):  ~{full_solver_3k_s:.1f} s")
    print(f"  Surrogate Speedup:           {speedup_ratio:.0f}x faster\n")

    # Generate Parity Plots
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    fig.suptitle(
        f"THERMA ML Surrogate Parity: ISO 52016-1 Physics Solver vs Neural Surrogate\n"
        f"(Trained on {meta['n_samples']} runs, tested on {len(X_test)} held-out samples)",
        fontsize=13,
        fontweight="bold",
    )

    plot_configs = [
        (0, "t_in_min_c", "Overnight Min Temp t_in_min (°C)", "°C", axes[0, 0]),
        (1, "t_in_max_c", "Daytime Max Temp t_in_max (°C)", "°C", axes[0, 1]),
        (2, "t_in_mean_c", "24h Mean Temp t_in_mean (°C)", "°C", axes[1, 0]),
        (3, "comfort_hours_ratio", "IMAC Comfort Ratio (0-1)", "ratio", axes[1, 1]),
    ]

    for t_idx, name, title, unit, ax in plot_configs:
        yt = y_test[:, t_idx]
        yp = y_pred[:, t_idx]
        m = eval_results["targets"][name]

        min_val = min(np.min(yt), np.min(yp))
        max_val = max(np.max(yt), np.max(yp))
        margin = 0.05 * (max_val - min_val) if max_val > min_val else 1.0

        # Scatter plot
        ax.scatter(yt, yp, alpha=0.35, color="#F77331", edgecolors="none", s=18, label="Test samples")
        # Identity line (y = x)
        ax.plot(
            [min_val - margin, max_val + margin],
            [min_val - margin, max_val + margin],
            "k--",
            lw=1.5,
            label="Ideal parity (y = x)",
        )

        ax.set_xlim(min_val - margin, max_val + margin)
        ax.set_ylim(min_val - margin, max_val + margin)
        ax.set_xlabel(f"ISO 52016-1 Ground Truth ({unit})", fontsize=10)
        ax.set_ylabel(f"ML Surrogate Prediction ({unit})", fontsize=10)
        ax.set_title(
            f"{title}\nR² = {m['r2']:.4f} | RMSE = {m['rmse']:.2f} {unit} | Max Err = {m['max_error']:.2f} {unit}",
            fontsize=10,
        )
        ax.grid(True, linestyle=":", alpha=0.6)
        ax.legend(loc="upper left", fontsize=8)

    plt.tight_layout()
    fig.savefig(PARITY_PLOT_PATH, dpi=180)
    plt.close(fig)
    print(f"Parity plot saved to: {PARITY_PLOT_PATH}")

    # Save trained model and metrics json
    surrogate.save(DEFAULT_MODEL_PATH)
    print(f"Surrogate model saved to: {DEFAULT_MODEL_PATH}")

    full_metrics = {
        "dataset_metadata": meta,
        "n_train": len(X_train_full),
        "n_test": len(X_test),
        "train_duration_s": train_duration_s,
        "eval_results": eval_results,
        "benchmarks": {
            "single_pred_ms": round(single_pred_ms, 3),
            "batch_3000_ms": round(batch_3k_ms, 2),
            "batch_3000_s": round(batch_3k_ms / 1000.0, 4),
            "full_solver_3000_s": full_solver_3k_s,
            "speedup_ratio": round(speedup_ratio, 1),
        },
    }

    with open(DEFAULT_METRICS_PATH, "w", encoding="utf-8") as f:
        json.dump(full_metrics, f, indent=2)
    print(f"Metrics saved to: {DEFAULT_METRICS_PATH}")

    return full_metrics


if __name__ == "__main__":
    train_and_evaluate()
